#!/bin/bash
# /etc/init.d/capsule

### BEGIN INIT INFO
# Provides:          capsule
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: capsule
# Description:       capsule
### END INIT INFO


case "$1" in
    start)
        echo "Starting capsule"
        /home/pi/capsule/index.js > /home/pi/tmp/capsule.log 2>&1 &
        ;;
    stop)
        echo "Stopping capsule"
        killall node # not the best way
        ;;
    *)
        echo "Usage: /etc/init.d/capsule start|stop"
        exit 1
        ;;
esac

exit 0
